name: Sync with Upstream Fork

on:
  # Run on a schedule (daily at 2 AM UTC)
  schedule:
    - cron: '0 2 * * *'
  
  # Allow manual trigger from Actions tab
  workflow_dispatch:
  
  # Run when changes are pushed to main (optional)
  push:
    branches:
      - main

jobs:
  sync:
    name: Sync main branch with upstream
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/once-ui-system/magic-portfolio.git || true
          git remote -v
      
      - name: Fetch upstream changes
        run: |
          git fetch upstream main
          echo "Fetched upstream changes"
      
      - name: Check for updates
        id: check
        run: |
          BEHIND=$(git rev-list --count HEAD..upstream/main)
          echo "commits_behind=$BEHIND" >> $GITHUB_OUTPUT
          echo "Main branch is $BEHIND commits behind upstream"
          
          if [ "$BEHIND" -gt 0 ]; then
            echo "has_updates=true" >> $GITHUB_OUTPUT
          else
            echo "has_updates=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Merge upstream changes
        if: steps.check.outputs.has_updates == 'true'
        run: |
          echo "Merging upstream/main into main..."
          git merge upstream/main --no-edit --allow-unrelated-histories || {
            echo "Merge conflict detected. Creating a pull request instead."
            exit 1
          }
      
      - name: Push changes
        if: steps.check.outputs.has_updates == 'true'
        run: |
          git push origin main
          echo "Successfully synced main branch with upstream"
      
      - name: Create PR on conflict
        if: failure()
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Sync with upstream fork'
          title: '🔄 Sync main branch with upstream fork'
          body: |
            This PR syncs the `main` branch with the upstream repository: `once-ui-system/magic-portfolio`.
            
            **Merge conflicts detected** - manual review required.
            
            ### Changes from Upstream
            - Review the changes from the upstream repository
            - Resolve any conflicts
            - Merge this PR to complete the sync
            
            ### What to do next
            1. Review the changes in this PR
            2. Resolve any merge conflicts
            3. Merge this PR to update your main branch
            4. Optionally merge main into develop to get upstream updates in your custom branch
            
            ---
            *This PR was automatically created by the sync-upstream workflow.*
          branch: sync-upstream-main
          base: main
          labels: |
            sync
            automated
      
      - name: Summary
        if: always()
        run: |
          if [ "${{ steps.check.outputs.has_updates }}" == "true" ]; then
            echo "✅ Sync completed: ${{ steps.check.outputs.commits_behind }} commits merged from upstream"
          else
            echo "✅ Already up to date with upstream"
          fi
